### ISSUE TITLE
 satisfy test: the server updates the user’s record with badge data (2 days)

### ISSUE THREAD

**Issue by andersonmmi** [andersonmmi/discourse-maker-badges-theme-component#1]

**Comment by morganstar** [comment]
Discord documentation on granting badges:
https://meta.discourse.org/t/how-to-grant-a-custom-badge-through-the-api/103270

**Comment by andersonmmi** [comment]
- [ ] Getter function returns all badge data for the logged in user
- [ ] grantBadges(Getter => response) using the built in badges api
- [ ] Story: New token comes into existence? When the admin adds the new badge, a script checks for the existence of that badge on all user profiles with addresses registerd.
