### ISSUE TITLE
Integrate with CDIP-18

### ISSUE THREAD

**Issue by andersonmmi** [andersonmmi/discourse-maker-badges-theme-component#14]
Integration with CDIP-18 requires the following steps:
- [ ] Parent Badges Represented on Discourse
- [ ] Link to DApp UI from Discourse
- [ ] Show unlocked badges in forum
- [ ] Update to V3 contract address

**Comment by dreamerxzz** [comment]
Link to CDIP 18 : https://github.com/scottrepreneur/Certificates/tree/maker/Maker
